# Find glslang
#
#  GLSLANG_FOUND
#  GLSLANG_INCLUDE_DIRS
#  GLSLANG_LIBRARIES

find_path(GLSLANG_INCLUDE_DIR NAMES glslang/Public/ShaderLang.h)
mark_as_advanced(GLSLANG_INCLUDE_DIR)

find_library(GLSLANG_LIBRARY NAMES glslang)
mark_as_advanced(GLSLANG_LIBRARY)

find_library(GLSLANG_SPIRV_LIBRARY NAMES SPIRV)
mark_as_advanced(GLSLANG_SPIRV_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
        GLSLang
        REQUIRED_VARS GLSLANG_LIBRARY GLSLANG_SPIRV_LIBRARY GLSLANG_INCLUDE_DIR)

if(GLSLANG_FOUND)
  set(GLSLANG_LIBRARIES ${GLSLANG_LIBRARY} ${GLSLANG_SPIRV_LIBRARY})
  set(GLSLANG_INCLUDE_DIRS ${GLSLANG_INCLUDE_DIR})
endif()
