# Find LibMagic
#
#  LIBMAGIC_FOUND
#  LIBMAGIC_INCLUDE_DIRS
#  LIBMAGIC_LIBRARIES

find_path(LIBMAGIC_INCLUDE_DIR NAMES magic.h)
mark_as_advanced(LIBMAGIC_INCLUDE_DIR)

find_library(LIBMAGIC_LIBRARY NAMES magic)
mark_as_advanced(LIBMAGIC_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
        LibMagic
        REQUIRED_VARS LIBMAGIC_LIBRARY LIBMAGIC_INCLUDE_DIR)

if(LIBMAGIC_FOUND)
  set(LIBMAGIC_LIBRARIES ${LIBMAGIC_LIBRARY})
  set(LIBMAGIC_INCLUDE_DIRS ${LIBMAGIC_INCLUDE_DIR})
endif()
